### ISSUE TITLE
npm postinstall: OCaml and preprocessor have incompatible versions

### ISSUE THREAD

**Issue by IwanKaramazow** [reasonml/rebel#10]
As mentioned on IRC:
`npm install jengaboot --save-dev`

Results in this post-install:

```
Fatal error: OCaml and preprocessor have incompatible versions
Fatal error: exception Misc.Fatal_error
```

I think I traced the source of the problem back to `refmt`, it's like it isn't available in the environment or so, when invoking `ocamlc`.
Apparently it's possible to do something like
`ocamlc somefile.ml`  in the post-install, however `ocamlc -pp refmt -impl somefile.re` will fail.
`refmt -parse re -print ml somefile.re && ocamlc somefile.ml` on the other hand will succeed.

I have no idea if this is specific to my computer.
As a workaround, I'm doing the following:

```
npm install --ignore-scripts
cd node_modules/jengaboot

// manually invoke in the post-install
ocamlfind ocamlc -pp refmt -linkpkg -package yojson -g -impl buildUtils/extractDeps.re -o buildUtils/extractDeps.out && ocamlfind ocamlc -pp refmt -linkpkg -package yojson -g -impl buildUtils/extractOpamDeps.re -o buildUtils/extractOpamDeps.out
```

A possible solution could be to change the post install to `"refmt -parse re -print ml buildUtils/extractDeps.re > buildUtils/extractDeps.ml && refmt -parse re -print ml buildUtils/extractOcamlfindDeps.re > buildUtils/extractOcamlfindDeps.ml && ocamlfind ocamlc -linkpkg -package yojson -g -impl buildUtils/extractDeps.ml -o buildUtils/extractDeps.out && ocamlfind ocamlc -linkpkg -package yojson -g -impl buildUtils/extractOcamlfindDeps.ml -o buildUtils/extractOcamlfindDeps.out"`. But it would probably be better to sort the `-pp refmt` problem out..

**Comment by chenglou** [comment]
Alright, I've reverted to precompiling and publishing the artifacts to circumvent this problem completely. The reason for not doing that (anymore) was that running the binary `./foo` will look for `ocamlrun` and use that runtime to execute the binary. That `ocamlrun` path defaults to `/usr/chenglou/blabla/ocamlrun`, information that was included during the compilation of the bin. So on everyone else's machine these binaries would fail to execute with "cannot find interpreter at /usr/chenglou/...` etc.

The solution is to simply force the `ocamlrun` path to be the end-user's: instead of `./foo`, do `ocamlrun ./foo`. See https://github.com/chenglou/jengaboot/commit/39b8359673c1473a47565dd55929e0ae4f968e3a#diff-a2d7009f8c7ab942b466cfd16a23c094R153

Published as `0.0.19`. Closing this and thanks for the report! Hopefully this works now.
